---

- import_role:
    name: 'ansible_plugins'

- name: Combine vnStat configuration inventory variables
  set_fact:
    vnstat_config_options: '{{ vnstat_config_options|combine(vnstat_group_config_options,vnstat_host_config_options) | default({}) }}'

- name: Install vnStat
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_items: '{{ vnstat_packages }}'

- name: Divert the original vnstat.conf configuration
  dpkg_divert:
    path: '/etc/vnstat.conf'
    state: 'present'

- name: Provide original /etc/vnstat.conf
  command: cp /etc/vnstat.conf.dpkg-divert /etc/vnstat.conf
  args:
    creates: '/etc/vnstat.conf'

- name: Configure vnStat number options
  lineinfile:
    dest: '/etc/vnstat.conf'
    regexp: '^{{ item.key }}'
    line: '{{ item.key }} {{ item.value }}'
  when: item.value is number
  with_dict: '{{ vnstat_config_options }}'
  notify: [ 'Reload vnstat' ]

- name: Configure vnStat string options
  lineinfile:
    dest: '/etc/vnstat.conf'
    regexp: '^{{ item.key }}'
    line: '{{ item.key }} "{{ item.value }}"'
  when: item.value is string
  with_dict: '{{ vnstat_config_options }}'
  notify: [ 'Reload vnstat' ]

- name: Initiate vnstat interfaces databases
  command: vnstat --update --iface '{{ item | quote }}'
  args:
    creates: '/var/lib/vnstat/{{ item }}'
  become: '{{ vnstat_user }}'
  with_flattened:
    - '{{ vnstat_interfaces }}'
    - '{{ vnstat_group_interfaces }}'
    - '{{ vnstat_host_interfaces }}'
